version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: miniproject
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mini
      MYSQL_USER: mini1234
      MYSQL_PASSWORD: mini1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mini-phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: mini1234
      PMA_PASSWORD: mini1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "9008:80"
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data: 
